version: '3.7'

services:
  verlihub:
    build: ../test/verlihub
    network_mode: host

  client:
    read_only: yes
    build:
      context: ../
      dockerfile: test-manual/client/Dockerfile
    network_mode: host
    tmpfs:
    - /share
