name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13", "1.14", "1.15"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - run: make test-nodocker

    - if: matrix.go == '1.15'
      run: bash <(curl -s https://codecov.io/bash)
